// ============================================================
// AirwayLab — Forum-Formatted Export
// Generates copy-paste text for ApneaBoard, r/SleepApnea, etc.
// ============================================================

import type { NightResult } from './types';
import type { Tier } from './auth/auth-context';
import { getTrafficLight } from './thresholds';
import { getStoredThresholds } from './threshold-overrides';
import { computeIFLRisk } from './ifl-risk';
import { computeEstimatedRDI } from './derived-metrics';
import { loadNightNotes } from './night-notes';

const RATING_LABELS: Record<number, string> = {
  1: 'Terrible',
  2: 'Poor',
  3: 'OK',
  4: 'Good',
  5: 'Great',
};

function tierBadge(tier?: Tier): string {
  if (tier === 'champion') return ' 🏆';
  if (tier === 'supporter') return ' 💚';
  return '';
}

function light(val: number, key: string): string {
  const THRESHOLDS = getStoredThresholds();
  const threshold = THRESHOLDS[key];
  if (!threshold) return '';
  const l = getTrafficLight(val, threshold);
  return l === 'good' ? '✅' : l === 'warn' ? '⚠️' : '🔴';
}

function fmt(n: number, dp = 1): string {
  return n.toFixed(dp);
}

function fmtHrs(h: number): string {
  const hrs = Math.floor(h);
  const mins = Math.round((h - hrs) * 60);
  return `${hrs}h ${mins}m`;
}

/**
 * Generate a markdown-style forum post summarising one night.
 */
export function exportForumSingleNight(n: NightResult, tier?: Tier): string {
  const lines: string[] = [];

  lines.push(`**AirwayLab Analysis — ${n.dateStr}**`);
  lines.push('');
  if (n.settings.settingsSource === 'unavailable') {
    lines.push('Settings: Not available (device type not supported or STR.edf missing)');
  } else {
    lines.push(`Machine: ${n.settings.deviceModel} | Mode: ${n.settings.papMode}`);
    if (n.settings.epap > 0) {
      lines.push(`Pressures: EPAP ${n.settings.epap} / IPAP ${n.settings.ipap} cmH₂O (PS ${n.settings.pressureSupport})`);
    }
  }
  lines.push(`Duration: ${fmtHrs(n.durationHours)} (${n.sessionCount} session${n.sessionCount !== 1 ? 's' : ''})`);
  lines.push('');

  // IFL Symptom Risk
  const iflRisk = computeIFLRisk(n);
  lines.push(`**IFL Symptom Risk: ${fmt(iflRisk)}% ${light(iflRisk, 'iflRisk')}**`);
  try {
    const notes = loadNightNotes(n.dateStr);
    if (notes.symptomRating !== null) {
      const label = RATING_LABELS[notes.symptomRating] ?? '';
      lines.push(`Sleep quality: ${notes.symptomRating}/5 (${label})`);
    }
  } catch { /* noop */ }
  lines.push('');

  // Glasgow
  lines.push('**Flow Limitation (Glasgow Index)**');
  lines.push(`Overall: ${fmt(n.glasgow.overall, 2)} ${light(n.glasgow.overall, 'glasgowOverall')}`);

  const comps = [
    ['Skew', n.glasgow.skew],
    ['Spike', n.glasgow.spike],
    ['Flat Top', n.glasgow.flatTop],
    ['Top Heavy', n.glasgow.topHeavy],
    ['Multi-Peak', n.glasgow.multiPeak],
    ['No Pause', n.glasgow.noPause],
    ['Insp Rate', n.glasgow.inspirRate],
    ['Multi-Breath', n.glasgow.multiBreath],
    ['Var Amp', n.glasgow.variableAmp],
  ] as const;
  lines.push(`Components: ${comps.map(([name, val]) => `${name} ${fmt(val, 2)}`).join(' | ')}`);
  lines.push('');

  // WAT
  lines.push('**Ventilation Analysis (WAT)**');
  lines.push(`FL Score: ${fmt(n.wat.flScore)}% ${light(n.wat.flScore, 'watFL')} | Regularity: ${Math.round(n.wat.regularityScore)}% ${light(n.wat.regularityScore, 'watRegularity')} | Periodicity: ${fmt(n.wat.periodicityIndex)}% ${light(n.wat.periodicityIndex, 'watPeriodicity')}`);
  lines.push('');

  // NED
  lines.push('**Breath Analysis (NED)**');
  const estRdi = computeEstimatedRDI(n.ned);
  lines.push(`NED Mean: ${fmt(n.ned.nedMean)}% ${light(n.ned.nedMean, 'nedMean')} | Combined FL: ${Math.round(n.ned.combinedFLPct)}% ${light(n.ned.combinedFLPct, 'combinedFL')} | RERA Index: ${fmt(n.ned.reraIndex)}/hr ${light(n.ned.reraIndex, 'reraIndex')}`);
  lines.push(`Est. RDI: ${fmt(estRdi)}/hr ${light(estRdi, 'estimatedRdi')} | H1 NED: ${fmt(n.ned.h1NedMean)}% | H2 NED: ${fmt(n.ned.h2NedMean)}%`);
  const boi = n.ned.briefObstructionIndex ?? 0;
  const hi = n.ned.hypopneaIndex ?? 0;
  if (boi > 0 || hi > 0) {
    lines.push(`Brief Obstruction Index: ${fmt(boi)}/hr ${light(boi, 'briefObstructionIndex')} | Hypopnea Index: ${fmt(hi)}/hr ${light(hi, 'hypopneaIndex')}`);
  }
  lines.push('');

  // Oximetry
  if (n.oximetry) {
    const ox = n.oximetry;
    lines.push('**Oximetry**');
    lines.push(`ODI-3: ${fmt(ox.odi3)}/hr ${light(ox.odi3, 'odi3')} | ODI-4: ${fmt(ox.odi4)}/hr ${light(ox.odi4, 'odi4')}`);
    lines.push(`T<90%: ${fmt(ox.tBelow90)} min ${light(ox.tBelow90, 'tBelow90')} | SpO₂ Mean: ${fmt(ox.spo2Mean)}% ${light(ox.spo2Mean, 'spo2Mean')}`);
    lines.push(`HR Clin 10: ${fmt(ox.hrClin10)}/hr ${light(ox.hrClin10, 'hrClin10')} | Coupled 3/10: ${fmt(ox.coupled3_10)}/hr`);
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by [AirwayLab](https://airwaylab.app)${tierBadge(tier)} — free, open-source PAP analysis*`);
  lines.push('*⭐ Star us on GitHub if AirwayLab helped you: [github.com/airwaylab-app/airwaylab](https://github.com/airwaylab-app/airwaylab)*');
  lines.push('*Not medical advice — discuss results with your clinician.*');

  return lines.join('\n');
}

/**
 * Generate a multi-night summary table for forum posts.
 */
export function exportForumMultiNight(nights: NightResult[], tier?: Tier): string {
  const lines: string[] = [];
  const sorted = [...nights].sort((a, b) => a.dateStr.localeCompare(b.dateStr));

  lines.push(`**AirwayLab Summary — ${sorted.length} Nights**`);
  lines.push(`(${sorted[0].dateStr} to ${sorted[sorted.length - 1].dateStr})`);
  lines.push('');
  lines.push(`Machine: ${sorted[0].settings.deviceModel} | Mode: ${sorted[0].settings.papMode}`);
  lines.push('');

  // Table header
  lines.push('| Date | Duration | IFL Risk | Glasgow | FL Score | NED Mean | RERA/hr | Est. RDI | BOI/hr | Regularity |');
  lines.push('|------|----------|----------|---------|----------|----------|---------|----------|--------|------------|');

  for (const n of sorted) {
    const ifl = computeIFLRisk(n);
    const boi = n.ned.briefObstructionIndex ?? 0;
    const rdi = computeEstimatedRDI(n.ned);
    lines.push(
      `| ${n.dateStr} | ${fmtHrs(n.durationHours)} | ${fmt(ifl)}% ${light(ifl, 'iflRisk')} | ${fmt(n.glasgow.overall, 2)} ${light(n.glasgow.overall, 'glasgowOverall')} | ${fmt(n.wat.flScore)}% | ${fmt(n.ned.nedMean)}% | ${fmt(n.ned.reraIndex)} | ${fmt(rdi)} ${light(rdi, 'estimatedRdi')} | ${fmt(boi)} | ${Math.round(n.wat.regularityScore)}% |`
    );
  }

  // Averages row
  const avg = (fn: (n: NightResult) => number) =>
    sorted.reduce((sum, n) => sum + fn(n), 0) / sorted.length;

  lines.push(
    `| **Average** | | **${fmt(avg((n) => computeIFLRisk(n)))}%** | **${fmt(avg((n) => n.glasgow.overall), 2)}** | **${fmt(avg((n) => n.wat.flScore))}%** | **${fmt(avg((n) => n.ned.nedMean))}%** | **${fmt(avg((n) => n.ned.reraIndex))}** | **${fmt(avg((n) => computeEstimatedRDI(n.ned)))}** | **${fmt(avg((n) => n.ned.briefObstructionIndex ?? 0))}** | **${Math.round(avg((n) => n.wat.regularityScore))}%** |`
  );

  lines.push('');

  // Oximetry table if any night has it
  const oxNights = sorted.filter((n) => n.oximetry);
  if (oxNights.length > 0) {
    lines.push('**Oximetry**');
    lines.push('| Date | ODI-3 | T<90% | SpO₂ Mean | HR Clin 10 |');
    lines.push('|------|-------|-------|-----------|------------|');
    for (const n of oxNights) {
      const ox = n.oximetry!;
      lines.push(
        `| ${n.dateStr} | ${fmt(ox.odi3)}/hr ${light(ox.odi3, 'odi3')} | ${fmt(ox.tBelow90)} min | ${fmt(ox.spo2Mean)}% | ${fmt(ox.hrClin10)}/hr |`
      );
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by [AirwayLab](https://airwaylab.app)${tierBadge(tier)} — free, open-source PAP analysis*`);
  lines.push('*⭐ Star us on GitHub if AirwayLab helped you: [github.com/airwaylab-app/airwaylab](https://github.com/airwaylab-app/airwaylab)*');
  lines.push('*Not medical advice — discuss results with your clinician.*');

  return lines.join('\n');
}
